services:
    _defaults:
        autowire: true
    DigipolisGent\Domainator9k\ServerTypes\CapistranoOpenmindsBundle\FieldType\CapistranoFileFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\ServerTypes\CapistranoOpenmindsBundle\FieldType\CapistranoFolderFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\ServerTypes\CapistranoOpenmindsBundle\FieldType\CapistranoSymlinkFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\ServerTypes\CapistranoOpenmindsBundle\FieldType\CapistranoCrontabLineFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\ServerTypes\CapistranoOpenmindsBundle\Provider\DataTypeProvider:
        tags:
            - { name: data_type_provider }
    DigipolisGent\Domainator9k\ServerTypes\CapistranoOpenmindsBundle\Provisioner\BuildProvisioner:
        tags:
            - { name: domainator.provisioner.build, priority: 30 }
    DigipolisGent\Domainator9k\ServerTypes\CapistranoOpenmindsBundle\Provisioner\DestroyProvisioner:
        tags:
           - { name: domainator.provisioner.destroy, priority: 40 }
